name: OAR_ML_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - scipy
  - pandas
  - astropy
  - seaborn
  - ipython
  - jupyter
  - pystan
  - pymc3
  - arviz
  - sklearn
  - corner
  - torch
  - pip
  - pip:
    - emcee==3.0rc2
    - astropy
    - astroquery
    - astroml
    - corner
